openapi: 3.0.3
info:
  title: Go Chi Swagger Testing
  description: |-
    Sample OpenApi yml config file presenting one way of testing application against definitions in that file.
  contact:
    email: grzegorz.lasak@grzegorzlasak.com
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  # !!! KEEP IN MIND TO UPDATE IT TO YOUR DOMAIN OR TO DELETE IT !!!
  # When using servers.url, you need to include full URL in the tests when building requests
  - url: https://to-be-defined.whoknows 
    description: Your server - to be defined.
paths:
  /api/ping:
    get:
      description: Our GET Ping endpoint
      tags:
        - PING
      operationId: getPing
      responses:
        '200':
          description: Our GET Ping response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ping:
                    type: string
                    example: pong
                    nullable: false
  /api/get-record/{id}:
    get:
      description: Our 404 Not Found response endpoint
      tags:
        - PING
      operationId: notFoundPing
      parameters:
        - in: path
          name: id
          required: true
          example: 12
          description: entity ID
          schema:
            type: integer
            format: uint64
      responses:
        '200':
          description: Our GET When record fount (id 5)
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 5
                    nullable: false
        '404':
          description: Our GET Not Found Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: err_not_found
                    nullable: false
                  error_msg:
                    type: string
                    example: Entity not found.
                    nullable: false
        '422':
          description: Invalid id param - Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: err_invalid_id
                    nullable: false
                  error_msg:
                    type: string
                    example: Id must be integer greater than 0..
                    nullable: false