# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' # Set your Go version here

      - name: Install dependencies
        run: go mod download

      - name: Set environment variables
        run: |
          echo "OPEN_API_CONFIG_FILE_PATH=${{ secrets.OPEN_API_CONFIG_FILE_PATH }}" >> .env

      - name: Run tests
        run: go test ./... -v -race
        env:
          MY_SECRET: ${{ vars.OPEN_API_CONFIG_FILE_PATH }}
